# Generated by Django 3.1 on 2021-02-28 05:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaries',
            name='address',
            field=models.TextField(default='ads'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaries',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salaries',
            name='department',
            field=models.CharField(default='testdep', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaries',
            name='designation',
            field=models.CharField(default='testdesignation', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaries',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 5, 12, 30, 219990, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaries',
            name='f_name',
            field=models.CharField(default='me', max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaries',
            name='name',
            field=models.CharField(default='bot', max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaries',
            name='salary',
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
    ]
