# Generated by Django 3.1 on 2021-02-28 05:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210228_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 28, 5, 14, 11, 751303, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
