# Generated by Django 3.1 on 2021-02-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210228_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaries',
            old_name='date',
            new_name='transaction_date',
        ),
    ]
