# Generated by Django 3.1 on 2021-02-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_salaries_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaries',
            name='dob',
        ),
    ]
