# Generated by Django 3.1.4 on 2021-01-09 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_student_rollno'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.IntegerField()),
                ('due_fees', models.IntegerField()),
                ('due_date', models.DateField(verbose_name='')),
                ('pay_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('rollno', models.IntegerField()),
                ('stu_class', models.CharField(max_length=23)),
                ('f_name', models.CharField(max_length=23)),
                ('m_name', models.CharField(max_length=23)),
                ('dob', models.DateField(verbose_name='')),
                ('address', models.TextField()),
                ('fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.studentfeesdetail')),
            ],
        ),
    ]
