# Generated by Django 3.1.4 on 2021-02-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_studentfeesdetail_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeesdetail',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.branch'),
        ),
    ]
