# Generated by Django 3.1.4 on 2021-01-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_studentdetail_studentfeesdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetail',
            old_name='dob',
            new_name='dateOfBirth',
        ),
    ]
