# Generated by Django 3.1 on 2021-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_course_fees_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
            ],
        ),
    ]
