# Generated by Django 3.1 on 2021-03-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_establishyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidfees',
            name='session_month',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidfees',
            name='session_year',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
