# Generated by Django 3.1.4 on 2021-01-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_auto_20210109_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeesdetail',
            name='pay_date',
            field=models.DateField(auto_now=True, verbose_name=''),
        ),
    ]
