# Generated by Django 3.1 on 2021-02-23 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_auto_20210223_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentFeesDetail',
            new_name='PaidFees',
        ),
        migrations.DeleteModel(
            name='StudentDetail',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fees',
        ),
        migrations.AddField(
            model_name='branchfees',
            name='exam_fees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='branchfees',
            name='library_charges',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='branchfees',
            name='tution_fees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp1.branch'),
            preserve_default=False,
        ),
    ]
