# Generated by Django 3.1.4 on 2021-01-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_auto_20210109_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='dateOfBirth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentfeesdetail',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentfeesdetail',
            name='pay_date',
            field=models.DateTimeField(),
        ),
    ]
