# Generated by Django 3.1.4 on 2021-01-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0006_auto_20210109_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=23)),
                ('fees', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='studentfeesdetail',
            old_name='due_fees',
            new_name='examFee',
        ),
        migrations.RemoveField(
            model_name='studentfeesdetail',
            name='due_date',
        ),
        migrations.AddField(
            model_name='studentfeesdetail',
            name='libraryCharges',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfeesdetail',
            name='maintenanceCharges1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfeesdetail',
            name='totalFee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfeesdetail',
            name='tutionFee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp1.studentcourse'),
            preserve_default=False,
        ),
    ]
