# Generated by Django 3.1 on 2021-02-24 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0011_auto_20210223_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidfees',
            old_name='totalFee',
            new_name='course_fee',
        ),
        migrations.RenameField(
            model_name='paidfees',
            old_name='examFee',
            new_name='exam_fee',
        ),
        migrations.RenameField(
            model_name='paidfees',
            old_name='libraryCharges',
            new_name='library_charges',
        ),
        migrations.RemoveField(
            model_name='paidfees',
            name='maintenanceCharges1',
        ),
        migrations.RemoveField(
            model_name='paidfees',
            name='tutionFee',
        ),
        migrations.AddField(
            model_name='paidfees',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp1.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidfees',
            name='total_fees',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidfees',
            name='tution_fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
