# Generated by Django 3.1 on 2021-02-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0012_auto_20210224_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidfees',
            old_name='total_fees',
            new_name='total_fee',
        ),
        migrations.AlterField(
            model_name='paidfees',
            name='pay_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
