# Generated by Django 3.1 on 2021-02-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0014_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(),
        ),
    ]
